# Generated by Django 4.2.4 on 2023-08-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Klass',
            new_name='Advent',
        ),
        migrations.RenameField(
            model_name='advent',
            old_name='updates_at',
            new_name='updated_at',
        ),
    ]
