# Generated by Django 4.2.4 on 2023-08-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0002_rename_klass_advent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advent',
            new_name='Advert',
        ),
    ]
