# Generated by Django 4.2.4 on 2023-08-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0004_advert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(default='', upload_to='adverts/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
